language: node_js
node_js:
  - "9"
  - "8"
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - npm run lint
script:
  - xvfb-run npm run test
  - xvfb-run npm run test:integration
  